include("./src/BRTSimulation.jl")

map = BRTSimulation.initialize()
BRTSimulation.print_map(map)
BRTSimulation.add_bus(map)
println()
BRTSimulation.print_map(map)
println("\nMoving first bus then adding next\n")
BRTSimulation.print_map(map)
BRTSimulation.calculating_next_speed(map)
BRTSimulation.move_bus!(map)
BRTSimulation.add_bus(map)
println()
BRTSimulation.print_map(map)
println()
println(map.buses)
println()
println("\nMoving first bus then adding next\n")
for i in 1:4
    BRTSimulation.calculating_next_speed(map)
    BRTSimulation.move_bus!(map)
    println(map.buses)
    BRTSimulation.add_bus(map)
    println()
    BRTSimulation.print_map(map)
end

println()
# BRTSimulation.calculating_next_speed(map.buses)
println(map.buses)